name: checkwebsite_websitedown
pack: checkwebsite
description: Sample rule firing on checkwebsite.websitedown 
enabled: true
trigger:
    type: checkwebsite.websitedown
action:
    ref: checkwebsite.startwebsite
    