name: on_checkwebsite_websitedown
pack: checkwebsite
description: Sample rule firing on checkwebsite.websitedown 
enabled: true
trigger:
    type: checkwebsite.websitedown
criteria:
        trigger.body.status:
            pattern: "OK"
            type: "equals"
action:
    ref: checkwebsite.startwebsite
    parameters:
      website: None
    